[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  HUGO_VERSION = "0.97.3"

[context.deploy-preview]
  command = "npm run build-preview"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
