baseURL: "https://julian.is"
title: "Courtney Gaviria — Marketing Operations"
footnoteReturnLinkContents: "↩"
permalinks:
  articles: /article/:slug/
  article-resources: /article/:slug/resources/
  work: /work/:slug/
params:
  Description: "Hey there, I'm Julian, a product designer and developer with a habit of experimenting."
  AuthorName: "Julian Gaviria"
  GitHubUser: "juliangav"
  images: ["/img/julian-signature-blue.jpg"]

taxonomies:
  tag: "tags"
  category: "categories"

markup:
  blackfriday:
    hrefTargetBlank: true
  goldmark:
    renderer:
      hardWraps: true
      unsafe: true
      xhtml: false

social:
  facebook_app_id: "275156446240779"
  twitter: "@juliangav"

security:
  funcs:
    getenv:
      - ^BRANCH
      - ^CONTEXT
