

baseURL: "https://julian.is"
title: "Julian Gaviria — Web Designer"
footnoteReturnLinkContents: "↩"
permalinks:
  articles: /article/:slug/
  article-resources: /article/:slug/resources/
params:
  Description: "Hey there, I'm Julian, a designer/developer who enjoys testing everything."
  AuthorName: "Julian Gaviria"
  GitHubUser: "juliangav"
  images: ["/img/julian-signature-blue.jpg"]

taxonomies:
  tag: "tags"
  category: "categories"

blackfriday:
 hrefTargetBlank: true

social: 
  facebook_app_id: "275156446240779"
  twitter: "@juliangav"

security:
  funcs:
    getenv:
      - ^BRANCH